import json

# Las 60 preguntas proporcionadas por el usuario
nuevas_preguntas_json = """[
  {"id": 1, "categoria": "Razonamiento Cuantitativo", "pregunta": "Un caracol debe llegar a la cima de un muro de 9 metros de alto; pero tiene la particularidad que en el día sube 3 metros y en la noche resbala un metro. ¿El día que llegará el caracol a la cima del muro es el?", "opciones": ["4°", "5°", "6°", "7°"], "respuesta_correcta": 0, "explicacion": "Análisis: Cada día efectivo sube 2m (3m sube - 1m baja). Día 1: llega a 2m. Día 2: llega a 4m. Día 3: llega a 6m. El Día 4, estando en 6m, sube sus 3m diarios y llega a 9m (la cima). Ya no resbala porque llegó.", "fuente": "Razonamiento Cuantitativo - Lic. Oscar Iván Martínez"},
  {"id": 2, "categoria": "Pedagógica - Evaluación", "pregunta": "Un docente observa que sus estudiantes tienen dificultades para aplicar un nuevo concepto. ¿Cuál es la acción más apropiada según los principios de la Evaluación Formativa?", "opciones": ["Asignarles más tarea para la casa como castigo por no comprender.", "Realizar una retroalimentación reflexiva para identificar el error y ajustar la enseñanza.", "Ignorar el error y continuar con el siguiente tema para no atrasarse.", "Bajarles puntos en la nota final para que estudien más."], "respuesta_correcta": 1, "explicacion": "La evaluación formativa busca mejorar el proceso de aprendizaje mediante la identificación de dificultades y la retroalimentación oportuna, no mediante el castigo o la calificación punitiva.", "fuente": "Material de estudio Concurso docente 2026"},
  {"id": 3, "categoria": "Aptitud Verbal - Analogías", "pregunta": "NUBE : EVAPORACIÓN ::", "opciones": ["mar : río", "desempleo : recesión", "sueño : cansancio", "oxidación : óxido"], "respuesta_correcta": 2, "explicacion": "Relación de Efecto a Causa (Producto : Proceso). La nube es producto de la evaporación. El sueño es producto (efecto) del cansancio. (Nota: En algunas claves se marca 'desempleo: recesión', pero la relación física más directa es sueño-cansancio).", "fuente": "Prueba APTITUD VERBAL 2016"},
  {"id": 4, "categoria": "Situacional - Convivencia", "pregunta": "En una escuela, la coincidencia del horario de descanso entre primaria y bachillerato genera agresiones. ¿Cuál es la medida más adecuada para abordar la situación integralmente?", "opciones": ["Implementar campañas educativas sobre buen comportamiento.", "Redistribuir el horario de descansos para que salgan a horas diferentes.", "Establecer zonas específicas de descanso para cada nivel con supervisión docente.", "Crear grupos de mediación donde los grandes ayuden a los pequeños."], "respuesta_correcta": 2, "explicacion": "Dado que el problema se agrava por el 'poco espacio' (contexto del caso), la solución estructural y preventiva más efectiva es la separación de espacios o tiempos (Zonificación/Horarios) para garantizar la seguridad física inmediata.", "fuente": "CARTILLA DE PREGUNTAS PRUEBA DOCENTE PEDAGÓGICA GENERAL"},
  {"id": 5, "categoria": "Razonamiento Cuantitativo", "pregunta": "Si dentro de 20 años tendré el triple de la edad que tenía hace 20 años, entonces tengo:", "opciones": ["20 años", "40 años", "60 años", "80 años"], "respuesta_correcta": 1, "explicacion": "Ecuación: Sea x la edad actual. (x + 20) = 3(x - 20). Resolviendo: x + 20 = 3x - 60 => 80 = 2x => x = 40.", "fuente": "Prueba Aptitud Numérica Final"},
  {"id": 6, "categoria": "Gestión Educativa - Inclusión", "pregunta": "En una institución educativa se identifica la necesidad de integrar estrategias para estudiantes con discapacidad. ¿Qué acción cumple con la normativa de inclusión?", "opciones": ["Crear un aula exclusiva para estudiantes con discapacidad.", "Implementar el Plan Individual de Ajustes Razonables (PIAR) y el DUA.", "Sugerir a las familias buscar instituciones especializadas.", "Eximir a estos estudiantes de las evaluaciones estandarizadas."], "respuesta_correcta": 1, "explicacion": "El Decreto 1421 de 2017 establece el PIAR y el Diseño Universal para el Aprendizaje (DUA) como herramientas obligatorias para la educación inclusiva, rechazando la segregación.", "fuente": "Simulacro de Referencia - Grufae"},
  {"id": 7, "categoria": "Aptitud Verbal - Ordenamiento", "pregunta": "Ordene las frases sobre 'La investigación cualitativa': 1. es altamente interpretativa 2. pero puede ser una rica fuente 3. se reúnen datos y se examinan 4. no puede arrojar conclusiones generales 5. toma una ruta exploratoria 6. en lugar de generar hipótesis previas.", "opciones": ["3, 6, 1, 2, 5, 4", "5, 6, 3, 1, 4, 2", "6, 1, 2, 5, 4, 3", "1, 4, 2, 3, 6, 5"], "respuesta_correcta": 1, "explicacion": "Orden lógico: Definición general (5) -> Contraste con método tradicional (6) -> Metodología (3) -> Característica (1) -> Limitación (4) -> Ventaja final (2).", "fuente": "Prueba APTITUD VERBAL 2016"},
  {"id": 8, "categoria": "Razonamiento Cuantitativo", "pregunta": "4 obreros trabajando 7 horas diarias construyen un muro en 3 días. ¿Cuántos días tardarán 2 obreros trabajando 6 horas diarias en construir un muro igual?", "opciones": ["4 días", "7 días", "9 días", "12 días"], "respuesta_correcta": 1, "explicacion": "Regla de tres compuesta. Total horas-hombre requeridas: 4*7*3 = 84 horas. Nueva capacidad diaria: 2*6 = 12 horas/día. Días necesarios: 84 / 12 = 7 días.", "fuente": "Razonamiento Cuantitativo - Lic. Oscar Iván Martínez"},
  {"id": 9, "categoria": "Pedagógica - Ciudadanía", "pregunta": "En Ciencias Sociales, para reconocerse como sujeto de derechos, ¿qué proceso debe priorizar el docente?", "opciones": ["La memorización de las leyes internacionales.", "El diseño de un mapa mental de las estructuras de gobierno.", "La deliberación, el análisis de dilemas éticos y la toma de postura.", "La realización de actividades físicas para el autocuidado."], "respuesta_correcta": 2, "explicacion": "La competencia ciudadana activa requiere pasar de la teoría a la práctica mediante la deliberación y el enfrentamiento a dilemas, fomentando el pensamiento crítico.", "fuente": "Material de estudio Concurso docente 2026"},
  {"id": 10, "categoria": "Psicotécnica - Liderazgo", "pregunta": "Ante la indisciplina por consumo de sustancias, la coordinadora busca aprovechar el talento docente. ¿Cuál es la mejor estrategia?", "opciones": ["Evaluar cada aporte con criterios objetivos y decidir ella misma.", "Priorizar las ideas de los docentes dispuestos a asumir la implementación.", "Implementar grupos pequeños para discutir y desarrollar las ideas más viables.", "Delegar el problema al orientador escolar exclusivamente."], "respuesta_correcta": 2, "explicacion": "El liderazgo distribuido promueve la participación colaborativa (grupos pequeños) para construir soluciones consensuadas, aumentando el compromiso del equipo.", "fuente": "CARTILLA DE PREGUNTAS PRUEBA DOCENTE"},
  {"id": 11, "categoria": "Razonamiento Cuantitativo", "pregunta": "Si por 12 camisetas pago 96 euros, ¿cuánto pagaré por 57 camisetas?", "opciones": ["400", "456", "500", "570"], "respuesta_correcta": 1, "explicacion": "Proporcionalidad directa. Costo unitario = 96 / 12 = 8 euros. Costo total = 57 * 8 = 456 euros.", "fuente": "Razonamiento Cuantitativo - Lic. Oscar Iván Martínez"},
  {"id": 12, "categoria": "Aptitud Verbal - Oraciones Incompletas", "pregunta": "La investigación cualitativa toma una ruta ________ más flexible, en lugar de generar hipótesis a partir de la investigación ________.", "opciones": ["exploratoria - previa", "rígida - futura", "matemática - actual", "subjetiva - experimental"], "respuesta_correcta": 0, "explicacion": "El contexto académico contrasta la flexibilidad cualitativa (exploratoria) con los métodos tradicionales que requieren hipótesis anteriores (previas).", "fuente": "Prueba APTITUD VERBAL 2016"},
  {"id": 13, "categoria": "Pedagógica - Planificación", "pregunta": "¿Qué se define inmediatamente después de la situación significativa en la programación curricular?", "opciones": ["Las actividades lúdicas.", "Los recursos y materiales.", "Seleccionar las Competencias, Capacidades y Desempeños a movilizar.", "La evaluación sumativa final."], "respuesta_correcta": 2, "explicacion": "En la planificación inversa, tras definir el reto (situación significativa), se debe establecer qué aprendizajes (competencias) se requieren para resolverlo antes de diseñar actividades.", "fuente": "Material de estudio Concurso docente 2026"},
  {"id": 14, "categoria": "Razonamiento Cuantitativo", "pregunta": "Ana va a la biblioteca cada 5 días y Miguel cada 3 días. Si hoy coincidieron, ¿en cuántos días volverán a coincidir?", "opciones": ["10 días", "12 días", "15 días", "20 días"], "respuesta_correcta": 2, "explicacion": "Mínimo Común Múltiplo (MCM). MCM(5, 3) = 15.", "fuente": "Razonamiento Cuantitativo - Lic. Oscar Iván Martínez"},
  {"id": 15, "categoria": "Legislación Educativa", "pregunta": "¿Cuál es la ley general que rige los fines de la educación en Colombia?", "opciones": ["Ley 1620", "Decreto 1278", "Ley 115 de 1994", "Ley 715"], "respuesta_correcta": 2, "explicacion": "La Ley 115 de 1994 es la Ley General de Educación. El Decreto 1278 es el estatuto docente, la 715 regula recursos y la 1620 convivencia.", "fuente": "Manual de Funciones - MEN"},
  {"id": 16, "categoria": "Razonamiento Cuantitativo", "pregunta": "Si un ladrillo pesa 4 kg, el peso de un ladrillito del mismo material cuyas dimensiones son 4 veces menores es:", "opciones": ["62.5 g", "125 g", "250 g", "500 g"], "respuesta_correcta": 0, "explicacion": "El volumen varía con el cubo de la proporción lineal. Si la dimensión es 1/4, el volumen es (1/4)³ = 1/64. Peso = 4000g / 64 = 62.5g.", "fuente": "prueba pedagogía con respuestas (1).pdf"},
  {"id": 17, "categoria": "Pedagógica - NEE", "pregunta": "Un estudiante con NEE tiene dificultades en lectura. ¿Cuál es la adaptación curricular adecuada?", "opciones": ["Eximirlo de las evaluaciones de lectura.", "Reducir la cantidad de texto sin modificar complejidad.", "Proporcionar textos con apoyo visual y simplificación del vocabulario.", "Hacer que repita el año para que madure."], "respuesta_correcta": 2, "explicacion": "La adaptación debe facilitar el acceso al currículo mediante ajustes razonables (apoyos visuales, simplificación) sin eliminar la competencia.", "fuente": "Material de estudio Concurso docente 2026"},
  {"id": 18, "categoria": "Aptitud Verbal - Antónimos", "pregunta": "BAQUIANO", "opciones": ["Primerizo", "Novato", "Torpe", "Incapaz"], "respuesta_correcta": 1, "explicacion": "Baquiano: Experto conocedor de caminos/terrenos. Antónimo directo: Novato.", "fuente": "GUÍA DE ORIENTACIÓN CNSC"},
  {"id": 19, "categoria": "Razonamiento Cuantitativo", "pregunta": "Juan vende limonada ganando $180 por vaso. Si vende 20 vasos por día, para ganar $12.600 tardará:", "opciones": ["3 días", "3.5 días", "4 días", "4.5 días"], "respuesta_correcta": 1, "explicacion": "Ganancia diaria = 20 vasos * $180 = $3600. Días requeridos = $12600 / $3600 = 3.5 días.", "fuente": "Razonamiento Cuantitativo - Lic. Oscar Iván Martínez"},
  {"id": 20, "categoria": "Situacional - Gestión", "pregunta": "Un colegio no ha establecido el gobierno escolar obligatorio. La directora teme sanciones. ¿Qué debe hacer?", "opciones": ["Delegar a un pequeño grupo la organización.", "Convocar a elecciones democráticas asegurando la participación de todos los estamentos.", "Posponer la creación hasta recibir directrices.", "Contratar una entidad externa."], "respuesta_correcta": 1, "explicacion": "El gobierno escolar (Ley 115, Art 142) es obligatorio y requiere la participación democrática de toda la comunidad educativa.", "fuente": "CARTILLA DE PREGUNTAS PRUEBA DOCENTE"},
  {"id":21,"categoria":"Razonamiento Cuantitativo","pregunta":"¿Qué hora es cuando el reloj marca los 5/6 de la mitad del triple de las 8:00 am?","opciones":["6:00 am","8:00 am","10:00 am","12:00 am"],"respuesta_correcta":2, "explicacion":"Triple de 8 = 24. Mitad de 24 = 12. 5/6 de 12 = 10. Son las 10:00 am.","fuente":"Razonamiento Cuantitativo - Lic. Oscar Iván Martínez"},
 {"id":22,"categoria":"Pedagógica - Metacognición","pregunta":"Para gestionar el aprendizaje autónomo, ¿qué tipo de preguntas debe promover el docente?","opciones":["Preguntas cerradas de memoria.","Preguntas metacognitivas: ¿Cómo aprendiste? ¿Qué dificultades tuviste?","Preguntas sobre la vida privada del autor.","Preguntas que exigen repetición literal."],"respuesta_correcta":1,"explicacion":"La metacognición (pensar sobre el propio pensamiento) es fundamental para desarrollar la autonomía y la autorregulación en el estudiante.","fuente":"Material de estudio Concurso docente 2026"},
  {"id":23,"categoria":"Razonamiento Cuantitativo","pregunta":"Mario debe 5/8 de $16.000.000 y paga los 3/4 de la deuda. ¿Cuánto debe aún?","opciones":["$2.500.000","$6.000.000","$7.500.000","$10.000.000"],"respuesta_correcta":0,"explicacion":"Deuda: 5/8 * 16m = 10m. Paga: 3/4 * 10m = 7.5m. Debe: 10m - 7.5m = 2.5 millones.","fuente":"Razonamiento Cuantitativo - Lic. Oscar Iván Martínez"},
 {"id":24,"categoria":"Aptitud Verbal - Sinónimos","pregunta":"DILAPIDAR","opciones":["Ahorrar","Poseer","Despilfarrar","Ganar"],"respuesta_correcta":2,"explicacion":"Dilapidar significa malgastar los bienes sin prudencia, sinónimo directo de despilfarrar.","fuente":"prueba pedagogía con respuestas (1).pdf"},
  {"id":25,"categoria":"Psicotécnica - Orientación","pregunta":"Ante un conflicto de agresión física repetida donde los padres usan castigo físico en casa sin éxito, ¿qué debe hacer la institución?","opciones":["Expulsar a los estudiantes.","Activar rutas de apoyo interinstitucional (ICBF/Comisaría) por posible vulneración de derechos.","Aplicar castigos más severos en el colegio.","Ignorar la situación familiar."],"respuesta_correcta":1,"explicacion":"Según la Ley 1620 y la Ley 1098, si hay vulneración de derechos (castigo físico severo) y la estrategia escolar no funciona, se debe activar la ruta externa.","fuente":"GUÍA DE ORIENTACIÓN CNSC"},
  {"id":26,"categoria":"Razonamiento Cuantitativo","pregunta":"Patricia es mayor que Claudia, y menor que Cristina, quien tiene la misma edad de Gloria. ¿Quién es la menor?","opciones":["Patricia","Claudia","Cristina","Gloria"],"respuesta_correcta":1,"explicacion":"Cristina = Gloria > Patricia > Claudia. La menor es Claudia.","fuente":"Razonamiento Cuantitativo - Lic. Oscar Iván Martínez"},
  {"id":27,"categoria":"Situacional - PEI","pregunta":"El PEI de una escuela no refleja las condiciones culturales de la comunidad. La directora decide:","opciones":["Contratar un experto externo.","Copiar el PEI de una escuela cercana.","Revisar y actualizar el PEI con la participación activa de toda la comunidad educativa.","Dejarlo así para evitar trámites."],"respuesta_correcta":2,"explicacion":"El Proyecto Educativo Institucional debe ser contextualizado y construido participativamente (Ley 115, Guía 34).","fuente":"CARTILLA DE PREGUNTAS PRUEBA DOCENTE"},
  {"id":28,"categoria":"Razonamiento Cuantitativo","pregunta":"Ayer 2 camiones transportaron mercancía. Hoy 3 camiones iguales harán 6 viajes para mover la misma cantidad. ¿Cuántos viajes hicieron ayer los 2 camiones?","opciones":["6","9","4","12"],"respuesta_correcta":1,"explicacion":"Total carga = 3 camiones * 6 viajes = 18 unidades de carga. Ayer: 18 unidades / 2 camiones = 9 viajes.","fuente":"Razonamiento Cuantitativo - Lic. Oscar Iván Martínez"},
  {"id":29,"categoria":"Pedagógica - TIC","pregunta":"El enfoque más pedagógico del uso de TIC en el aula es:","opciones":["Reemplazar al docente con videos.","Usarlas como herramientas cognitivas para colaboración e indagación.","Restringir su uso a diapositivas.","Usarlas solo para premios."],"respuesta_correcta":1,"explicacion":"Las TIC deben potenciar el aprendizaje activo, la investigación y el trabajo colaborativo, no ser un fin en sí mismas.","fuente":"Material de estudio Concurso docente 2026"},
  {"id":30,"categoria":"Razonamiento Cuantitativo","pregunta":"Si 10 autos consumen 10 galones en 10 horas, ¿cuántos galones consume 1 auto en 1 hora?","opciones":["1/100","1/10","1","10"],"respuesta_correcta":1,"explicacion":"10 autos en 10 horas = 10 galones. 1 auto en 10 horas = 1 galón. 1 auto en 1 hora = 1/10 de galón.","fuente":"Razonamiento Cuantitativo - Lic. Oscar Iván Martínez"},
  {"id":31,"categoria":"Aptitud Verbal - Oraciones Incompletas","pregunta":"Los perros, gatos y otras plagas _____ también los animales de granja, son especies que dependen para su supervivencia de la especie humana _____ por su alto grado de domesticación.","opciones":["y / ;",", y / ,",", o / ,","; / y"],"respuesta_correcta":1,"explicacion":"La estructura enumera grupos (coma + y) y luego explica la causa tras una coma explica tiva o causal implícita.","fuente":"Prueba APTITUD VERBAL 2016"},
  {"id":32,"categoria":"Situacional - Convivencia","pregunta":"Un estudiante consumió licor dentro del colegio. El manual estipula expulsión. El docente decide:","opciones":["Hacerle firmar un compromiso para no delatarlo.","Dialogar con el psicólogo e investigar qué anda mal en su vida privada (Debido Proceso).","Expulsarlo inmediatamente.","Castigarlo físicamente."],"respuesta_correcta":1,"explicacion":"Aunque la falta sea grave, el debido proceso y el enfoque formativo (Ley 1620) exigen indagar causas y ofrecer apoyo psicosocial antes o durante la sanción.","fuente":"60 preguntas para concurso de reubicación docente"},
  {"id":33,"categoria":"Razonamiento Cuantitat ivo","pregunta":"Se sabe que tres obreros tardan 8, 6 y 4 horas en pintar una casa individualmente. ¿Cuánto tiempo tardan juntos?","opciones":["Entre 1 y 2 horas","6 horas","18 horas","1.84 horas"],"respuesta_correcta":3,"explicacion":"Sumar velocidades (1/8 + 1/6 + 1/4) = (3+4+6)/24 = 13/24 casas por hora. Tiempo = 24/13 ≈ 1.84 horas.","fuente":"prueba pedagogía con respuestas (1).pdf"},
  {"id":34,"categoria":"Pedagógica - Inclusión","pregunta":"En un aula hay dos grupos de rendimiento muy diferenciado. ¿Qué est rategia es pertinente?","opciones":["Enseñar solo al nivel promedio.","Separarlos en dos aulas distintas.","Reconocer la diversidad y brindar acompañamiento diferenciado (andamiaje) a quienes tienen dificultades mientras reta a los avanzados.","Ignorar a los de bajo rendimiento."],"respuesta_correcta":2,"explicacion":"La pertinencia pedagógica implica atender la diversidad dentro del aula mediante estrategias diferenciadas sin segregar.","fuente":"60 preguntas para concurso de reubicación docente"},
  {"id":35,"categoria":"Razonamiento Cuantitativo","pregunta":"El 20% del 40% de una cantidad equivale al:","opciones":["60%","20%","30%","8%"],"respuesta_correcta":3,"explicacion":"0.20 * 0.40 = 0.08, que equivale al 8%.","fuente":"prueba pedagogía con respuestas (1).pdf"},
  {"id":36,"categoria":"Gestión - PEI","pregunta":"¿Cuál es el principal indicador de que el PEI es efectivo?","opciones":["El número de reuniones realizadas.","Que los resultados de aprendizaje se alineen con la visión y objetivos del PEI.","La cantidad de dinero invertido en infraestructura.","El cumplimiento estricto de horarios."],"respuesta_correcta":1,"explicacion":"La gestión escolar se mide por resultados de calidad (aprendizajes) y su coherencia con la misión institucional (Guía 34).","fuente":"Material de estudio Concurso docente 2026"},
  {"id":37,"categoria":"Razonamiento Cuantitativo","pregunta":"Un padre tiene 3 veces la edad de su hijo. Hace 10 años tenía 5 veces la edad. ¿Edad del hijo?","opciones":["20","30","40","50"],"respuesta_correcta":0,"explicacion":"P = 3H. Hace 10 años: (P-10) = 5(H-10). Sustituyendo: 3H -  10 = 5H - 50 -> 40 = 2H -> H = 20.","fuente":"Razonamiento Cuantitativo - Lic. Oscar Iván Martínez"},
  {"id":38,"categoria":"Pedagógica - Didáctica","pregunta":"¿Qué proceso es central para la competencia 'Construye interpretaciones históricas'?","opciones":["Memorizar fechas.","Lectura y contraste crítico de diversas fuentes.","Hacer resúmenes de un solo libro.","Ver películas de época."],"respuesta_correcta":1,"explicacion":"La historia se construye interpretando fuentes diversas y contrastando perspectivas, no memorizando datos aislados.","fuente":"Material de estudio Concurso docente 2026"},
  {"id":39,"categoria":"Razonamiento Cuantitativo","pregunta":"Pedro usa 1/4 del día en tareas, 1/6 en deporte y 1/9 con amigos. ¿Qué parte le queda libre?","opciones":["17/36","12/25","18/36","19/36"],"respuesta_correcta":0,"explicacion":"Suma de gastos: 1/4 + 1/6 + 1/9 = (9+6+4)/36 = 19/36. Libre = 1 - 19/36 = 17/36.","fuente":"prueba pedagogía con respuestas (1).pdf"},
  {"id":40,"categoria":"Legislación - Evaluación","pregunta":"Según la normativa colombiana, la evaluación de los estudiantes en los niveles de básica y media debe ser:","opciones":["Cualitativa, integral y continua.","Solo sumativa y final.","Exclusivamente memorística.","Dependiente del pago de pensión."],"respuesta_correcta":0,"explicacion":"El Decreto 1290 (y sus antecedentes) promueve una evaluación formativa, integral y continua, superando la mera calificación numérica final.","fuente":"Manual de Funciones - MEN"},
  {"id":41,"categoria":"Razonamiento Cuantitativo","pregunta":"Tres anuncios se encienden a intervalos de 12, 15 y 18 minutos. Si coinciden a las 2:00 pm, ¿a qué hora repiten?","opciones":["5:00 pm","4:00 pm","3:30 pm","6:00 pm"],"respuesta_correcta":0,"explicacion":"MCM(12, 15, 18) = 180 minutos. 180 min = 3 horas. 2:00 pm + 3 horas = 5:00 pm.","fuente":"Razonamiento Cuantitativo - Lic. Oscar Iván Martínez"},
  {"id":42,"categoria":"Pedagógica - Planificación","pregunta":"Al planificar una unidad didáctica, el docente debe considerar primero:","opciones":["El libro de texto.","Los intereses, necesidades y saberes previos de los estudiantes.","La decoración del aula.","Las fechas de vacaciones."],"respuesta_correcta":1,"explicacion":"El aprendizaje significativo parte de conectar los nuevos saberes con el contexto y los conocimientos previos del estudiante.","fuente":"Material de estudio Concurso docente 2026"},
  {"id":43,"categoria":"Aptitud Verbal - Comprensión","pregunta":"Si un texto argumentativo defiende la eutanasia, una idea contraria sería:","opciones":["El derecho a morir dignamente.","La autonomía del paciente.","La sacralidad de la vida por encima de la libertad individual.","El alivio del sufrimiento."],"respuesta_correcta":2,"explicacion":"La sacralidad de la vida es el argumento ético/religioso clásico que se opone a la disposición de la propia vida (eutanasia).","fuente":"Inferido de textos de Aptitud Verbal"},
  {"id":44,"categoria":"Psicotécnica - Trabajo en Equipo","pregunta":"Un docente critica constantemente a sus colegas en reuniones. Como coordinador, usted debe:","opciones":["Ignorarlo para no crear conflicto.","Abordarlo en privado para retroalimentar sobre comunicación asertiva y respeto.","Criticarlo públicamente para que aprenda.","Expulsarlo de las reuniones."],"respuesta_correcta":1,"explicacion":"La competencia comportamental de liderazgo y comunicación exige abordar los conflictos de manera constructiva y privada para mejorar el clima laboral.","fuente":"Manual de Funciones - Competencias Comportamentales"},
  {"id":45,"categoria":"Razonamiento Cuantitativo","pregunta":"Una familia de 6 adultos tiene comida para 15 días. Llegan 3  adultos más. ¿Para cuántos días alcanza ahora?","opciones":["10 días","12 días","9 días","8 días"],"respuesta_correcta":0,"explicacion":"Regla de tres inversa. (6 personas * 15 días) = 90 raciones. Ahora hay 9 personas. 90 / 9 = 10 días.","fuente":"Razonamiento Cuantitativo - Lic. Oscar Iván Martínez"},
  {"id":46,"categoria":"Pedagógica - Ambiente de Aula","pregunta":"Para fomentar un clima de aula democrático, el docente debe:","opciones":["Imponer normas estrictas sin discusión.","Permitir que los estudiantes participen en la construcción de los acuerdos de convivencia.","Dejar que los estudiantes hagan lo que quieran (Laissez-faire).","Elegir un delegado que mande a los demás."],"respuesta_correcta":1,"explicacion":"La convivencia democrática se basa en la participación y el consenso normativo, no en la imposición ni en el desorden.","fuente":"Material de estudio Concurso docente 2026"},
  {"id":47,"categoria":"Razonamiento Cuantitativo","pregunta":"El largo del puente A es 3 veces el largo del puente B. Si suman 120 metros, el puente más largo mide:","opciones":["30 m","40 m","80 m","90 m"],"respuesta_correcta":3,"explicacion":"A + B = 120. A = 3B. Entonces 3B + B = 120 -> 4B = 120 -> B = 30. A = 3(30) = 90m.","fuente":"GUÍA DE ORIENTACIÓN CNSC - Aptitud Numérica"},
  {"id":48,"categoria":"Pedagógica - EIB","pregunta":"En un contexto de educación intercultural (EIB), el docente debe:","opciones":["Prohibir la lengua materna.","Utilizar la lengua materna como puente para el aprendizaje y valorar la cultura local.","Enseñar solo la cultura occidental.","Ignorar el contexto cultural."],"respuesta_correcta":1,"explicacion":"El enfoque EIB exige el respeto y uso pedagógico de la lengua y cultura originarias para un aprendizaje pertinente.","fuente":"Material de estudio Concurso docente 2026"},
  {"id":49,"categoria":"Razonamiento Cuantitativo","pregunta":"Un tanque de 1200 cm3 está lleno 3/4 en invierno y 2/3 en verano. La diferencia es:","opciones":["100 cm3","200 cm3","300 cm3","120 cm3"],"respuesta_correcta":0,"explicacion":"Invierno: 3/4 de 1200 = 900. Verano: 2/3 de 1200 = 800. Diferencia: 900 - 800 = 100 cm3.","fuente":"GUÍA DE ORIENTACIÓN CNSC - Aptitud Numérica"},
  {"id":50,"categoria":"Aptitud Verbal - Ordenamiento","pregunta":"Ordene la oración: 1. lleva 2. esa 3. alegre 4. muñeca 5. a 6. su 7. infancia 8. la","opciones":["2, 4, 8, 1, 5, 6, 3, 7","6, 3, 4, 8, 1, 5, 2, 7","2, 3, 7, 8, 1, 5, 6, 4","6, 7, 8, 1, 5, 2, 3, 4"],"respuesta_correcta":0,"explicacion":"'Esa muñeca la lleva a su alegre infancia' construye el sentido completo.","fuente":"GUÍA DE ORIENTACIÓN CNSC - Aptitud Verbal"},
  {"id":51,"categoria":"Pedagógica - Ética","pregunta":"Según la ética docente, frente a los resultados de evaluación, el deber es:","opciones":["Ocultarlos hasta el final.","Usarlos para clasificar a los alumnos.","Comunicarlos y usarlos para la mejora continua (retroalimentación).","Ignorar los."],"respuesta_correcta":2,"explicacion":"La evaluación debe ser transparente y tener un fin formativo de mejoramiento, no solo administrativo.","fuente":"Material de estudio Concurso docente 2026"},
  {"id":52,"categoria":"Razonamiento Cuantitativo","pregunta":"Si un círculo tiene radio 10 cm, su área es (pi = 3.14):","opciones":["31.4","314","100","62.8"],"respuesta_correcta":1,"explicacion":"Área = pi * r². A = 3.14 * (10²) = 3.14 * 100 = 314 cm².","fuente":"Conocimiento General Matemático"},
  {"id":53,"categoria":"Situacional - Rectoría","pregunta":"El rector debe decidir entre construir una piscina o una pista de patinaje. ¿Qué debe hacer?","opciones":["Decidir según su gusto personal.","Realizar un estudio técnico y consultar las necesidades e intereses de la comunidad educativa.","Hacer una rifa.","Preguntar solo a los padres."],"respuesta_correcta":1,"explicacion":"La gestión de recursos debe responder a un diagnóstico de necesidades y al bienestar de la comunidad (Gestión Directiva/Comunitaria).","fuente":"CARTILLA DE PREGUNTAS PRUEBA DOCENTE PEDAGÓGICA GENERAL"},
  {"id":54,"categoria":"Razonamiento Cuantitativo","pregunta":"En una reunión, la mitad son mujeres, de ellas 1/6 son altas. Si hay 36 personas, ¿cuántas mujeres NO son altas?","opciones":["12","15","3","18"],"respuesta_correcta":1,"explicacion":"Total 36. Mujeres = 18. Altas = 1/6 de 18 = 3. No altas = 18 - 3 = 15.","fuente":"Razonamiento Cuantitativo - Lic. Oscar Iván Martínez"},
  {"id":55,"categoria":"Pedagógica - Evaluación","pregunta":"El uso de rúbricas detalladas compartidas previamente con los estudiantes favorece:","opciones":["Que el docente trabaje menos.","La autoevaluación y la claridad sobre los objetivos de aprendizaje.","Que todos saquen la misma nota.","La memorización."],"respuesta_correcta":1,"explicacion":"La rúbrica es un instrumento de evaluación formativa que guía al estudiante sobre qué se espera de él, fomentando la autorregulación.","fuente":"02 - CARTILLA DE PREGUNTAS DOCENTE PRIMARIA"},
  {"id":56,"categoria":"Aptitud Verbal - Comprensión","pregunta":"En un texto sobre 'El futuro del libro', si el autor dice que el libro es una extensión de la memoria, implica que:","opciones":["Los libros ocupan mucho espacio.","Los libros permiten preservar el conocimiento humano a través del tiempo.","La memoria humana es infinita.","Los libros son obsoletos."],"respuesta_correcta":1,"explicacion":"La metáfora 'extensión de la memoria' alude a la función de almacenamiento y transmisión cultural de la escritura.","fuente":"prueba pedagogía con respuestas (1).pdf"},
  {"id":57,"categoria":"Razonamiento Cuantitativo","pregunta":"Si a/b = 2/3 y b/c = 3/5, entonces a/c es:","opciones":["2/5","5/2","6/15","1/3"],"respuesta_correcta":0,"explicacion":"(a/b) * (b/c) = a/c. (2/3) * (3/5) = 6/15 = 2/5.","fuente":"Conocimiento General Matemático"},
  {"id":58,"categoria":"Legislación - Manual de Convivencia","pregunta":"Según la Ley 1620, el Manual de Convivencia debe:","opciones":["Ser un listado de castigos.","Construirse participativamente y definir la ruta de atención integral.","Copiar el código de policía.","Ser redactado solo por el rector."],"respuesta_correcta":1,"explicacion":"El manual es una herramienta de construción colectiva que regula la convivencia y define rutas de promoción, prevención y atención.","fuente":"Manual de Funciones - MEN"},
  {"id":59,"categoria":"Razonamiento Cuantitativo","pregunta":"Un vendedor recibe un sueldo base más 10% de comisión. Si vendió 10 millones y recibió 2 millones en total, su sueldo base es:","opciones":["1 millón","800 mil","1.2 millones","500 mil"],"respuesta_correcta":0,"explicacion":"Comisión = 10% de 10m = 1 millón. Total (2m) = Base + Comisión (1m). Base = 1 millón.","fuente":"Razonamiento Cuantitativo - Lic. Oscar Iván Martínez"},
  {"id":60,"categoria":"Pedagógica - Motivación","pregunta":"Un estudiante no participa en clase por miedo a equivocarse. El docente debe:","opciones":["No preguntarle nunca para no incomodarlo.","Crear un clima de confianza donde el error sea visto como parte del aprendizaje.","Oblig arlo a participar para que pierda el miedo.","Bajarle puntos por no participar."],"respuesta_correcta":1,"explicacion":"La seguridad psicológica es requisito para el aprendizaje. El docente debe naturalizar el error como oportunidad de mejora (Evaluación Formativa).","fuente":"60 preguntas para concurso de reubicación docente"}
]"""

nuevas_preguntas = json.loads(nuevas_preguntas_json)

# Leer el archivo actual
with open('quizData2.js', 'r', encoding='utf-8') as f:
    content = f.read()

# Encontrar el punto de inserción (antes del cierre del array de questions)
insert_point = content.rfind('    ]\n};')

if insert_point == -1:
    print("Error: No se encontró el punto de inserción")
    exit(1)

# Construir las nuevas preguntas en el formato correcto
letras = ['a', 'b', 'c', 'd', 'e', 'f']
nuevas_preguntas_js = []

for i, preg in enumerate(nuevas_preguntas, start=36):
    # Determinar la dificultad basándose en la categoría
    if 'Razonamiento' in preg['categoria'] or 'Cuantitativo' in preg['categoria']:
        difficulty = 'hard'
    elif 'Pedagógica' in preg['categoria'] or 'Situacional' in preg['categoria']:
        difficulty = 'expert'
    else:
        difficulty = 'hard'
    
    # Construir answerOptions
    answer_options_str = ""
    for j, opcion in enumerate(preg['opciones']):
        is_correct = (j == preg['respuesta_correcta'])
        rationale = preg['explicacion'] if is_correct else "Esta no es la respuesta correcta. " + preg['explicacion']
        
        # Escapar comillas
        opcion_clean = json.dumps(opcion)[1:-1]  # json.dumps escapa automáticamente
        rationale_clean = json.dumps(rationale)[1:-1]
        
        if j > 0:
            answer_options_str += ",\n"
        answer_options_str += '                {\n'
        answer_options_str += f'                    "text": "{opcion_clean}",\n'
        answer_options_str += f'                    "rationale": "{rationale_clean}",\n'
        answer_options_str += f'                    "isCorrect": {str(is_correct).lower()}\n'
        answer_options_str += '                }'
    
    correct_answer = letras[preg['respuesta_correcta']]
    
    # Escapar comillas
    pregunta_clean = json.dumps(preg['pregunta'])[1:-1]
    explicacion_clean = json.dumps(preg['explicacion'])[1:-1]
    fuente_clean = json.dumps(preg['fuente'])[1:-1]
    categoria_clean = json.dumps(preg['categoria'])[1:-1]
    
    pregunta_js = '        ,\n        {\n'
    pregunta_js += f'            "questionNumber": {i},\n'
    pregunta_js += f'            "category": "{categoria_clean}",\n'
    pregunta_js += f'            "difficulty": "{difficulty}",\n'
    pregunta_js += f'            "question": "{pregunta_clean}",\n'
    pregunta_js += '            "answerOptions": [\n'
    pregunta_js += answer_options_str + '\n'
    pregunta_js += '            ],\n'
    pregunta_js += f'            "correctAnswer": "{correct_answer}",\n'
    pregunta_js += f'            "rationale": "{explicacion_clean}",\n'
    pregunta_js += f'            "hint": "Fuente: {fuente_clean}"\n'
    pregunta_js += '        }'
    
    nuevas_preguntas_js.append(pregunta_js)

# Agregar las nuevas preguntas
nuevo_contenido = content[:insert_point] + ''.join(nuevas_preguntas_js) + '\n' + content[insert_point:]

# Guardar el archivo
with open('quizData2.js', 'w', encoding='utf-8') as f:
    f.write(nuevo_contenido)

print(f"✓ Agregadas {len(nuevas_preguntas)} preguntas a quizData2.js")
print(f"✓ Archivo actualizado: questionNumber 1-{35 + len(nuevas_preguntas)}")
