-- ==========================================
-- CONFIGURACIÓN COMPLETA DE SUPABASE (SIMULACRO 2026)
-- Copia y pega esto en el SQL Editor de Supabase
-- ==========================================

-- 0. FUNCIÓN PARA EVITAR RECURSIÓN (is_admin)
-- Esta función corre con permisos de sistema (SECURITY DEFINER) para evitar el error de recursion infinita
CREATE OR REPLACE FUNCTION public.check_is_admin()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.user_roles
    WHERE user_id = auth.uid() AND role = 'admin'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 1. TABLA DE ROLES (user_roles)
CREATE TABLE IF NOT EXISTS public.user_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL UNIQUE,
    email TEXT UNIQUE,
    role TEXT DEFAULT 'free' CHECK (role IN ('admin', 'free', 'premium')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Habilitar RLS en user_roles
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- Políticas para user_roles
DROP POLICY IF EXISTS "Usuarios pueden ver su propio rol" ON public.user_roles;
CREATE POLICY "Usuarios pueden ver su propio rol" ON public.user_roles
    FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Admins pueden gestionar todo en user_roles" ON public.user_roles;
CREATE POLICY "Admins pueden gestionar todo en user_roles" ON public.user_roles
    FOR ALL USING (public.check_is_admin());

-- 2. TABLA DE CATÁLOGO (simulacros)
CREATE TABLE IF NOT EXISTS public.simulacros (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    numero INTEGER UNIQUE NOT NULL,
    titulo TEXT NOT NULL,
    descripcion TEXT,
    total_preguntas INTEGER DEFAULT 0,
    es_premium BOOLEAN DEFAULT FALSE,
    activo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Habilitar RLS en simulacros
ALTER TABLE public.simulacros ENABLE ROW LEVEL SECURITY;

-- Políticas para simulacros (Lectura pública o para autenticados)
DROP POLICY IF EXISTS "Lectura pública de simulacros activos" ON public.simulacros;
CREATE POLICY "Lectura pública de simulacros activos" ON public.simulacros
    FOR SELECT USING (activo = true);

-- Insertar datos iniciales si no existen (Simulacros 1, 2 y 3)
INSERT INTO public.simulacros (id, numero, titulo, descripcion, total_preguntas, es_premium)
VALUES 
    ('d15c2a06-b97f-4349-817b-14e07377a0e6', 1, 'Simulacro General', 'Evaluación completa de competencias para el concurso docente.', 360, false),
    (gen_random_uuid(), 2, 'Simulacro Premium 2', 'Preguntas avanzadas y casos de estudio específicos.', 95, true),
    (gen_random_uuid(), 3, 'Simulacro Experto 3', 'Preguntas de alta complejidad y análisis curricular profundo.', 60, true)
ON CONFLICT (numero) DO NOTHING;


-- 3. TABLA DE PROGRESO V2 (simulacro_progress_v2)
CREATE TABLE IF NOT EXISTS public.simulacro_progress_v2 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    simulacro_id UUID REFERENCES public.simulacros(id) ON DELETE CASCADE,
    progress_data JSONB DEFAULT '{}'::jsonb,
    score INTEGER DEFAULT 0,
    last_index INTEGER DEFAULT 0,
    total_correctas INTEGER DEFAULT 0,
    total_incorrectas INTEGER DEFAULT 0,
    total_respondidas INTEGER DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    UNIQUE(user_id, simulacro_id)
);

-- Habilitar RLS en simulacro_progress_v2
ALTER TABLE public.simulacro_progress_v2 ENABLE ROW LEVEL SECURITY;

-- Políticas para simulacro_progress_v2
DROP POLICY IF EXISTS "Usuarios gestionan su propio progreso" ON public.simulacro_progress_v2;
CREATE POLICY "Usuarios gestionan su propio progreso" ON public.simulacro_progress_v2
    FOR ALL USING (auth.uid() = user_id);


-- 4. FUNCIÓN ESPECIAL PARA ELIMINAR USUARIOS (Auth)
-- Esta función permite que un administrador elimine a un usuario de la tabla auth.users
-- Se debe llamar vía RPC: supabase.rpc('delete_user_entirely', { target_user_id: '...' })
CREATE OR REPLACE FUNCTION delete_user_entirely(target_user_id UUID)
RETURNS VOID AS $$
BEGIN
    -- Verificar si quien llama es Admin usando la funcion de seguridad
    IF public.check_is_admin() THEN
        DELETE FROM auth.users WHERE id = target_user_id;
    ELSE
        RAISE EXCEPTION 'No tienes permisos para realizar esta acción.';
    END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Otorgar permisos a usuarios autenticados para ejecutar la función (la función misma valida si es admin)
GRANT EXECUTE ON FUNCTION delete_user_entirely(UUID) TO authenticated;

-- 5. PERMISOS GENERALES
GRANT ALL ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role;
GRANT USAGE ON SCHEMA public TO authenticated;
